### ISSUE TITLE
ログイン時にタイムアウトが発生する

### ISSUE THREAD

**Issue by nakahararuu** [nakahararuu/hide_nsfw4p#1]
どこかのタイミングでデグレが発生した…？

```
$ ~/g/p/g/n/hide_nsfw4p (main)> npm start

> hide_nsfw4p@0.0.1 start
> node main.js

node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
    at loginAndStoreAuthenticationState (/Users/nakahararuu/ghq/private/github.com/nakahararuu/hide_nsfw4p/main.js:10:8)
    at async openBookmarkPage (/Users/nakahararuu/ghq/private/github.com/nakahararuu/hide_nsfw4p/main.js:29:3)
    at async /Users/nakahararuu/ghq/private/github.com/nakahararuu/hide_nsfw4p/main.js:42:15 {
  name: 'TimeoutError'
}
```

**Comment by nakahararuu** [comment]
ログインボタン押せてないっぽい。テスト実行時は問題ないので、おそらくレンダリングをwaitすればよい

**Comment by nakahararuu** [comment]
privateブラウジングでログインを試みたらrecaptchaが表示されたのでこれが原因っぽい…
以前は表示されなかったはずなので、おそらくログイン回数やアクセス回数が閾値を超えたアカウントで発生すると思われる。しばらく静観。

**Comment by nakahararuu** [comment]
2021/09/09 時点でrecaptchaが表示されなくなったことを確認。本Issueはいつでも対応可能。

**Comment by nakahararuu** [comment]
recaptchaの問題解消後に施行してみたが結果は変わらず。
6324eb60121d2730c653c2bd2301aef888429e7c にてデバッグ用の実装を行い確認したところ、適切なフォントがインストールされておらずログイン画面が文字化けしていることが確認できた。

ID/Passwordの入力フォームやログインボタンは[テキストセレクタ](https://playwright.dev/docs/selectors#text-selector)で選択しているため、文字化けによって要素の選択ができなくなっていたと思われる。

5f599d3efb166e131f2eed91bf98c77ef1e96f89 にてフォントをインストールして対応済み。
